name: jup110
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - asn1crypto
  - attrs
  - blas
  - bleach
  - bokeh
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - conda=4.7.10
  - conda-env
  - conda-package-handling
  - cryptography
  - cycler
  - dbus
  - decorator
  - entrypoints
  - expat
  - fastcache
  - fontconfig
  - freetype
  - glib
  - gmp
  - gmpy2
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - ipykernel
  - ipython_genutils
  - jinja2
  - jpeg
  - jupyter_client=5.3.1
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterthemes
  - kiwisolver
  - lesscpy
  - libarchive
  - libffi
  # - libgcc-ng
  - libgfortran-ng
  - libpng
  - libsodium
  # - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - lzo
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl_fft
  - mkl_random
  - mkl-service
  - mpc
  - mpfr
  - mpmath
  - nbconvert
  - ncurses
  - nodejs
  - numpy
  - numpy-base
  - olefile
  - openssl
  - packaging
  - pandas
  - pandoc
  - panel
  - param
  - patsy
  - pcre
  - pexpect
  - pillow
  - pip
  - ply
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pycosat
  - pycparser
  - pyct
  - pyct-core
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python=3.6.7
  - python-dateutil
  - python-libarchive-c
  - pytz
  - pyviz_comms
  - pyyaml
  - qt
  - readline
  - requests
  - ruamel_yaml
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - statsmodels
  - sympy
  - testpath
  - tk
  - tqdm
  - urllib3
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
    - alembic
    - async-generator
    - backcall
    - certipy
    - defusedxml
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyterhub
    - jupyterlab
    - jupyterlab-server
    - mako
    - nbformat
    - nbgitpuller
    - nbresuse
    - notebook
    - nteract-on-jupyter
    - oauthlib
    - pamela
    - pandocfilters
    - parso
    - pickleshare
    - prometheus-client
    - psutil
    - pyrsistent
    - python-editor
    - pyzmq
    - sqlalchemy
    - terminado
    - tornado
    - traitlets
    - wcwidth
    - webencodings
    - widgetsnbextension

